const LOCATION_SYNC_QUEUE_LIMIT = 250;
const LOCATION_SYNC_MAX_ATTEMPTS_PER_ITEM = 3;
const LOCATION_SYNC_FLUSH_BATCH_LIMIT = 20;

export {
  LOCATION_SYNC_FLUSH_BATCH_LIMIT,
  LOCATION_SYNC_MAX_ATTEMPTS_PER_ITEM,
  LOCATION_SYNC_QUEUE_LIMIT,
};
